#!/bin/bash
# .claude/skills/icc-pipes/scripts/list
# list: one line per pipe, "DIR up" or "DIR down".
# Up means the hold still has lane 0 open.
# Copyright (c) 2026 Brian Case. All rights reserved.
# AI contributor: Claude (Anthropic)
#
# MIT License text omitted for brevity, See LICENCE.TXT
for pDir in /tmp/icc-pipes-*/; do
  [ -d "$pDir" ] || continue
  pDir=${pDir%/}
  [ -p "$pDir/0" ] || continue
  pidHold=$(cat "$pDir/pid" 2>/dev/null)
  eState=down
  [ "$(readlink "/proc/$pidHold/fd/3" 2>/dev/null)" = "$pDir/0" ] && eState=up
  echo "$pDir $eState"
done
